[pytest]
filterwarnings =
    ignore:.*__fields__.*:pydantic.warnings.PydanticDeprecatedSince20:cohere.*
    ignore:.*model_fields.*:pydantic.warnings.PydanticDeprecatedSince211:cohere.*
    ignore:.*parse_obj.*:pydantic.warnings.PydanticDeprecatedSince20:cohere.*
